"""empty message

Revision ID: e5ecc6d6eeac
Revises: d6a0655f832b
Create Date: 2025-07-29 22:52:42.860591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5ecc6d6eeac'
down_revision = 'd6a0655f832b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.alter_column('event_status',
               existing_type=postgresql.ENUM('COMPLETE', 'ERROR', 'PENDING', name='event_status'),
               type_=sa.Enum('COMPLETE', 'ERROR', 'PENDING', name='status'),
               existing_nullable=False)
        batch_op.alter_column('event_type',
               existing_type=postgresql.ENUM('RESYNC', 'UPDATE', name='event_type'),
               type_=sa.Enum('RESYNC', 'UPDATE', name='type'),
               existing_nullable=False)

    with op.batch_alter_table('solr_synonym_lists', schema=None) as batch_op:
        batch_op.alter_column('synonym_type',
               existing_type=postgresql.ENUM('ADDRESS', 'NAME', 'ALL', name='syn_type'),
               type_=sa.Enum('ALL', name='type'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solr_synonym_lists', schema=None) as batch_op:
        batch_op.alter_column('synonym_type',
               existing_type=sa.Enum('ALL', name='type'),
               type_=postgresql.ENUM('ADDRESS', 'NAME', 'ALL', name='syn_type'),
               existing_nullable=False)

    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('RESYNC', 'UPDATE', name='type'),
               type_=postgresql.ENUM('RESYNC', 'UPDATE', name='event_type'),
               existing_nullable=False)
        batch_op.alter_column('event_status',
               existing_type=sa.Enum('COMPLETE', 'ERROR', 'PENDING', name='status'),
               type_=postgresql.ENUM('COMPLETE', 'ERROR', 'PENDING', name='event_status'),
               existing_nullable=False)

    # ### end Alembic commands ###
